# Generated by Django 2.0.3 on 2018-04-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='loctime',
            field=models.DateTimeField(),
        ),
    ]
