# Generated by Django 2.0.3 on 2018-04-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_auto_20180410_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
